version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: infra/backend.Dockerfile
    container_name: goodhamburger-api
    ports:
      - "5269:8080"
    volumes:
      - ./data:/app/data
    networks:
      - goodhamburger-network

  frontend:
    build:
      context: .
      dockerfile: infra/frontend.Dockerfile
    container_name: goodhamburger-web
    ports:
      - "5151:80"
    depends_on:
      - backend
    networks:
      - goodhamburger-network

networks:
  goodhamburger-network:
    driver: bridge
